### ISSUE TITLE
Be handy to be able to set a type on a property

### ISSUE THREAD

**Issue by djomen** [zpqrtbnk/Zbu.ModelsBuilder#10]
So that we don't have object - on a content picker for example we could set int for the node id.

Or would it be better to just implement the property ourselves and ask the Builder to ignore? I guess if we did it ourselves then we can go the extra mile and spin up a proper type.

**Comment by sukhdev22** [comment]
any example? i can't find any example ?
how to get my image url, it returns integer only?

**Comment by zpqrtbnk** [comment]
@sukhdev22 if I understand correctly, you would like an example of a property converters that returns the image url instead of the integer, right?

**Comment by sukhdev22** [comment]
exactly @zpqrtbnk ,
It should give me url automatically, not integer
