### ISSUE TITLE
Error on 'Run Custom Tool": 'Response status code does not indicate success (NotFound)'

### ISSUE THREAD

**Issue by hfloyd** [zpqrtbnk/Zbu.ModelsBuilder#100]
Hi Stephan, 
Let me know if you'd rather have this in the Umbraco YouTrack issues. Since it applies to using the Visual Studio add-in, I thought I'd put it here.

So, I have "Tools > Options... > Umbraco > Models Builder" pointing to my website.

When I "Run Custom Tool" ("UmbracoModelsBuilder") on the ModelsBuilder.cs file I have set up, I get this error in the VS Output Window:
    
    UmbracoModelsBuilder: Starting v3.0.0.90 3/7/2016 3:46:28 PM.
    UmbracoModelsBuilder: UmbracoModelsBuilder failed to generate code: Exception: Response status code does not indicate success (NotFound)
    
    UmbracoModelsBuilder:at Umbraco.ModelsBuilder.Api.ApiClient.EnsureSuccess(HttpResponseMessage result)
       at Umbraco.ModelsBuilder.Api.ApiClient.ValidateClientVersion()
       at Umbraco.ModelsBuilder.CustomTool.CustomTool.UmbracoModelsBuilder.GenerateRaw(String wszInputFilePath, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, String& errMsg)

My web.config options look like this:

    <add key="Umbraco.ModelsBuilder.Enable" value="true" />
    <add key="Umbraco.ModelsBuilder.ModelsMode" value="" />
     
    <add key="Umbraco.ModelsBuilder.EnableApi" value="true" />
    <add key="Umbraco.ModelsBuilder.StaticMixinGetters" value="true" />

The relevant NuGet packages I have installed: 

- **Umbraco Website Project:**
	- UmbracoCms.7.4.1
	- UmbracoCms.Core.7.4.1
	- Umbraco.ModelsBuilder.3.0.0
	- Umbraco.ModelsBuilder.Api.3.0.0
- **Separate Code Project (compiled into a dll for Umbraco Website Project - Includes ModelsBuilder.cs file using Custom Tool):**
	- UmbracoCms.Core.7.4.1
	- Umbraco.ModelsBuilder.3.0.0
	- Umbraco.ModelsBuilder.Api.3.0.0

I'm not sure what is missing here...

Thanks!
Heather

**Comment by hfloyd** [comment]
Ah, nevermind!

I figured out that the issue was that some custom model partials in the project had build errors. Once I fixed those and rebuilt, I was able to run the Custom Tool.

**Comment by zpqrtbnk** [comment]
Ah, you're doing everything by yourself, you don't need me anymore ;-))

**Comment by hfloyd** [comment]
Haha! Ah, Stephan, we will ALWAYS need you! :-)
