### ISSUE TITLE
More that one type want to be a model for content type message

### ISSUE THREAD

**Issue by okolokolo** [zpqrtbnk/Zbu.ModelsBuilder#101]
I keep getting this error message "More that one type want to be a model for content type BucketsFolder" when I trying to generate models from ModelsBuilder

using this configuration 

 <add key="Umbraco.ModelsBuilder.Enable" value="true" />
 <add key="Umbraco.ModelsBuilder.ModelsMode" value="AppData" />
  <add key="Zbu.ModelsBuilder.EnableAppDataModels" value="true" />

Can you explain to me what I'm doing wrong?

Thanks

**Comment by zpqrtbnk** [comment]
The configuration is not rendering?

Usually, it means that more than 1 class marked with attribute `[PublishedContentModel("bucketsFolder")]` have been found when inspecting the assemblies.

What models mode are you using?

**Comment by okolokolo** [comment]
I think I have figured it out I had to add this to my web.config
 <add key="Zbu.ModelsBuilder.EnablePublishedContentModelsFactory" value="false"/>

**Comment by okolokolo** [comment]
I think I have figured in out I had to set
Zbu.ModelsBuilder.EnablePublishedContentModelsFactory to false in my webconfig

**Comment by zpqrtbnk** [comment]
Er... this would entirely disable the models factory, and therefore models. Not sure that's what you want?

What mode are you using? Do you have models in a DLL? In Visual Studio? How are you using the Models Builder?

**Comment by okolokolo** [comment]
I have Zbu.ModelsBuilder.EnableDllModels set to true
Right now we are just using ModelBuilder to generate models from our document types

**Comment by zpqrtbnk** [comment]
EnableDllModels means that when you "generate" a DLL is created in ~/bin containing the models. Are you _also_ compiling the generated models eg in a Visual Studio solution?

**Comment by okolokolo** [comment]
And Yes the models have been add to the Visual Studio project

**Comment by zpqrtbnk** [comment]
Then they are compiled twice, once in the DLL and once in your project. If you "just" want to get the source code you want the EnableAppDataModels option that will generate them, but not compile them (and remember to delete the DLL from bin!)

**Comment by okolokolo** [comment]
Okay thanks!
