### ISSUE TITLE
Incorrect example code

### ISSUE THREAD

**Issue by richarth** [zpqrtbnk/Zbu.ModelsBuilder#105]
The introduction [https://github.com/zpqrtbnk/Zbu.ModelsBuilder/wiki/Umbraco.ModelsBuilder] implies you can do:

@Model.BodyText

To get the EndDate property of my model I had to do:

@Model.Content.EndDate

Should the example be updated to:

```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.NewsItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}
<h1>@Model.Content.Title</h1>
@Model.Content.BodyText
```

**Comment by zpqrtbnk** [comment]
Depends on what the view inherits from. If it inherits from `UmbracoTemplatePage<NewsItem>` then the actual content is `Model.Content` and therefore you have to do `@Model.Content.Title`. On the other hand if it inherits from `UmbracoViewPage<NewsItem>` then the actual content is `Model` itself and you can do `@Model.Title`.

**Comment by richarth** [comment]
I think it might be worth mentioning both options.  The model builder/Umbraco generated my view inheriting from UmbracoTemplatePage so I was thrown for a bit until I saw your post [http://www.zpqrtbnk.net/posts/beyond-purelive](http://www.zpqrtbnk.net/posts/beyond-purelive).

**Comment by zpqrtbnk** [comment]
Right - keeping the issue open so I remember to update the docs! Thanks!

**Comment by zpqrtbnk** [comment]
Have updated the wiki page you mentioned with a note right under the first code sample, about the two different view classes. Hope it's cleared like this.
