### ISSUE TITLE
Upgrade to latest Roslyn

### ISSUE THREAD

**Issue by zpqrtbnk** [zpqrtbnk/Zbu.ModelsBuilder#106]
Currently running on 1.0 and should upgrade to 1.x (latest).

**Comment by zpqrtbnk** [comment]
ModelsBuilder for version 8 now uses the very latest Roslyn. For version 7 things are more complicated: latest Roslyn (2.9 as of today) will not install on a Framework 4.5 project, and MB has to remain 4.5 as Umbraco 7 itself is 4.5. We _could_ try to go to an intermediate 1.x version but... these versions introduce all sorts of weird binding redirects on libraries.

Am afraid not going to do this on 7.

**Comment by ronaldbarendse** [comment]
Keep in mind that the application project (where Umbraco and Models Builder are installed to) can still be a higher .NET version and allow installing a newer versions of Microsoft.CodeAnalysis.* :smile:

**Comment by neoKushan** [comment]
@ronaldbarendse For clarification, installing a newer version of Microsoft.CodeAnalysis.* doesn't fix or workaround #165 (and I suspect #151). It's useful to know for some use-cases, but sadly I think most of us are just going to be waiting for v8.
