### ISSUE TITLE
Use GeneratedCodeAttribute to minimize build warnings

### ISSUE THREAD

**Issue by ThumNet** [zpqrtbnk/Zbu.ModelsBuilder#107]
What would you think about adding the [GeneratedCode](https://msdn.microsoft.com/en-gb/library/system.codedom.compiler.generatedcodeattribute.aspx) attribute to the generated code?

I'm asking this because currently our build is flooded with warnings from the generated models.
![image](https://cloud.githubusercontent.com/assets/692308/14688706/41e4818e-0744-11e6-847e-e8797d221972.png)

Please note the correct usage of the attribute as specified [here](https://blogs.msdn.microsoft.com/codeanalysis/2007/04/27/correct-usage-of-the-compilergeneratedattribute-and-the-generatedcodeattribute/)

If this is something you'd like to add I can create a pull request.

Regards,
Jeffrey

**Comment by zpqrtbnk** [comment]
Definitively make sense, wasn't aware of these attributes. Will do.

**Comment by zpqrtbnk** [comment]
Notes

Reading from the post mentioned by Jeffrey, the attribute we want to use is `GeneratedCodeAttribute` in `System.CodeDom.Compiler`, specifying the name and version of the generator. It should not "_be applied at the type level if the type being generated is a partial class_" which means we cannot apply it to each model class, but would need to apply it to each method and property inside the class.

**Comment by ThumNet** [comment]
Great this is going into the next-minor! 

Are you adding the code yourself or should I create the pull request?

**Comment by zpqrtbnk** [comment]
A PR always helps ;-) It can be a bit painful though as you'd have to add the attribute on each property and method of each model class, not on the model class itself, as it is a partial class.

**Comment by ThumNet** [comment]
I know it's a bit of work, but I think I can manage :) When is your next minor release planned?

**Comment by zpqrtbnk** [comment]
No plan really. When I have enough interesting bits to release I guess ;-)

**Comment by zpqrtbnk** [comment]
Oh my this is old - finally merged / ported the changes to v3 (used by Umbraco 7) and v8 (used by Umbraco 8) - so it *will* make it, next time Core updates its dependencies. Thanks!
