### ISSUE TITLE
Can not extend Model with Umbraco 7 

### ISSUE THREAD

**Issue by Sid0007** [zpqrtbnk/Zbu.ModelsBuilder#108]
Version : 7.4.2  and 7.4.3

Settings: 	
<add key="Umbraco.ModelsBuilder.Enable" value="true" />
<add key="Umbraco.ModelsBuilder.EnableApi" value="true" />
<add key="Umbraco.ModelsBuilder.ModelsMode" value="AppData" />
 and also tried with "DLL" and "LiveAppData"

1. step 

Created a Model in root and added class News copied from generated cs as follows

1. Generated CS

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>News</summary>
	[PublishedContentModel("news")]
	public partial class News : PublishedContentModel, IDataMigration
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "news";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109
}

Created as follows

namespace Umbraco.Web.PublishedContentModels
{
     public partial class News
    {
         public string Test 
           {
                      get {    // can not access any property from generated cs
                       }
        }
    }
}

also tried creating with App_data/Models  but no luck.  I think there is also raised a bug in Umbraco Under http://issues.umbraco.org/issue/U4-8043#

I have also tried with latest version. But no luck  :( 

It is throwing an error with multiple classes and can not bind when extend from existing generated class.

Regards
Sid

**Comment by zpqrtbnk** [comment]
Afraid I don't understand it all. Hope you don't mind a few questions.

What does "_Created a Model in root and added class News copied from generated cs as follows_" mean? Why would you "copy" class news, and what is "root"? Where _exactly_ would the News.generated.cs and News.cs files be? Can you copy/paste/screenshot the errors that you are seeing?

**Comment by Sid0007** [comment]
Thanks Stephen.

As per your previous post  "Your own partial classes need to be in App_Data/Models in order to get compiled and then it should work."

It is working now as it expected when you create new class within folder

Regards
