### ISSUE TITLE
Exception is nowhere to be found

### ISSUE THREAD

**Issue by LennardF1989** [zpqrtbnk/Zbu.ModelsBuilder#110]
I have constant issues with ModelBuilder failing to build, but I can't find the actual error anywhere, even though it says to check the Umbraco log. The Umbraco widget is said to show the latest error, it doesn't.

I have also tried to use the Console-tool, it generates just fine, but it doesn't compile it to a DLL for me, which is why the Umbraco generator is handy.

**Comment by LennardF1989** [comment]
Update: After pulling my hair for over 2 hours, I noticed a small models.err file in the App_Data/Models folder, this contained exactly the issue I needed. It did however never show up on the dashboard widget as expected.

**Comment by zpqrtbnk** [comment]
Weird. So there _is_ a `models.err` fine in App_Data/Models but no error is reported in the dashboard? Can you tell me what Models Builder config you have in web.config?

**Comment by LennardF1989** [comment]
Correct, and I didn't change a thing compared to the default Umbraco installation.

**Comment by zpqrtbnk** [comment]
Closing this issue, as it is quite (too) old. Please come back to me if you think it's still valid!
