### ISSUE TITLE
Model builder generates non-partial classes in Dll mode.

### ISSUE THREAD

**Issue by sebglow** [zpqrtbnk/Zbu.ModelsBuilder#112]
Hi. 
I used dotPeek to see the model generated by ModelBuilder. And I realized that the model has been generated as non-partial classes. Is that ok? Is there any way to force ModelBuidler to generate partial classes in "Dll" mode.

Thanks
Sebastian

**Comment by zpqrtbnk** [comment]
All models should be generated as partial classes. That is, the _source code_ indicates that the classes are partial classes. When compiling, all partial source code bits are assembled into one class, and "partial" does not make much sense at binary level. So... it would be normal that dotPeek cannot expose that the class is partial. What you want to look at is the source.

**Comment by sebglow** [comment]
You are absolutely right, and what I tried to do was stupid. I forgot that I can't have partial across assemblies. As you said - partial does not make sense at binary level.
I'm sorry for that confusion. And of course many thanks for quick response.
