### ISSUE TITLE
Use private backing fields to "cache" property values

### ISSUE THREAD

**Issue by DanDiplo** [zpqrtbnk/Zbu.ModelsBuilder#116]
Currently when a property is exposed on a model the code generates something like:

```
public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
{
    get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
}
```

However, each time this property is access then the value has to be fetched from the cache, go through a property converter to serialise it to a class, and then returned.

So if you wrote something like this in your Razor:

```
@if (Model.UmbracoFile != null)
{
    <div class="image">
        <img src="@Model.UmbracoFile.Url" width="100" height="50" />
    </div>
}
```

then the property would have to be fetched twice (once for the null check and once when displayed). This isn't that efficient.

It would be nice if the properties could be generated something like:

```
private Umbraco.Web.Models.ImageCropDataSet _umbracoFile = null;

public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
{
    get
    {
        if (_umbracoFile == null)
        {
            _umbracoFile = this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile");
        }

        return _umbracoFile;
    }
}
```

That way they are only retrieved on the first access and subsequent accessed aren't penalised with the hit. I guess it would only work with reference types. Though you could be clever and for value types wrap the private backing field as nullable type and then return the actual value in the property, something like:

```
private int? _someNumber = null;

public int SomeNumber
{
    get
    {
        if (_someNumber == null)
        {
            _someNumber = this.GetPropertyValue<int>("someNumber", default(int));
        }

        return _someNumber.Value;
    }
}
```

**Comment by zpqrtbnk** [comment]
>However, each time this property is access then the value has to be fetched from the cache, go through a property converter to serialise it to a class, and then returned.

This is not correct, I think. Converted values are cached, at least at `IPublishedContent` level, so once `Model.UmbracoFile` has been retrieved once and convertion to `ImageCropDataSet` has happened... it should not happen twice. Hence, no need to backing fields.

Making sense?

(I know this is an *old* issue.... trying to clean things up)
