### ISSUE TITLE
Can't seem to be able to use assembly attributes

### ISSUE THREAD

**Issue by doronuziel71** [zpqrtbnk/Zbu.ModelsBuilder#117]
Hi,

I'm trying to set the base class to be  of type BaseContent

have added this line to AssemblyInfo.cs

`[assembly: ModelsBaseClass(typeof(BaseContent))]`

Yet when I try to generate models, (I've tried both AppData, or using Visual Studio custom Tool)

The models still apear to be inheriting from  PublishedContentModel

Am I missing something?

Thanks,
Doron

**Comment by zpqrtbnk** [comment]
Sorry for the horribly late reply. The line should be added to a .cs file alongside the models, ie some sort of Models.cs file in the same directories the files are generated in.

Making sense?

**Comment by doronuziel71** [comment]
Ok.

Thanks alot.

I will give this a try.

**Comment by zpqrtbnk** [comment]
Cool, it works by all my tests, so closing the issue - but in case of any problem, just reopen it!
