### ISSUE TITLE
Change output location of dll

### ISSUE THREAD

**Issue by oneprince** [zpqrtbnk/Zbu.ModelsBuilder#121]
Is there a way to specify the output location of the DLL that gets generated via the Dll or LiveDll mode?

Good practice is to not place generated DLLs in GIT, specifically in the bin folder.  A build server will compile okay and push out to an environment, but the views will crash because the DLL is missing.

**Comment by zpqrtbnk** [comment]
Quick answer is, no way at the moment - but could be added.

Just so I understand, where would you put the DLL so that it is not missing on the build server?

**Comment by oneprince** [comment]
Right now, we use the LiveDLL setting when we are developing so that we can have strongly typed classes and code completion while working on Views.  We currently just take the generated DLL from the bin folder and place it in a manually created DLLs folder.  We added that DLL as a reference at the project level so that when the project builds (like on the build server) it pulls the DLL from that folder.  (qa servers are set to just DLL mode as we don't make data changes there.)  The issue with this is pretty much that manual step of copying the DLL from the bin folder to the DLLs folder.  If you forget... bad things happen (aka, views crash up on the qa servers, etc...).  We are thinking of just adding some code to the app startup to copy the DLL for us.  Just wanted to see if there was a better way before going that route.  Are we going about this wrong?  Is there a better mode that gives us the benefits of using a DLL locally but are also friendly for CIS?

**Comment by zpqrtbnk** [comment]
Makes sense to generate to another folder and reference the DLL in the project, so that views have intellisense and the DLL is deployed in bin when the project is built. Keeping this as a feature request.

**Comment by zpqrtbnk** [comment]
merged PR, fixed!
many thanks!
