### ISSUE TITLE
How to use the the ModelsBuilder Custom Tool?

### ISSUE THREAD

**Issue by HarveyWilliams** [zpqrtbnk/Zbu.ModelsBuilder#125]
I have installed the [ModelsBuilder Custom Tool](https://marketplace.visualstudio.com/items?itemName=ZpqrtBnk.UmbracoModelsBuilderCustomTool) extension on my Visual Studio.

I have also installed the Umbraco.ModelsBuilder.Api package onto my web project. I already had Umbraco.ModelsBuilder installed.

I have also in the Web.config set `<add key="Umbraco.ModelsBuilder.EnableApi" value="true" />`.

However, I'm not sure where to go from here. There doesn't seem to be any documentation on how to use this tool, but if I understand correctly, I can build models from inside of VS rather than needing to log into Umbraco?

Is there a documentation page somewhere?

**Comment by zpqrtbnk** [comment]
You should find more infos on the API on [this wiki page](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/wiki/Builder-Modes). Let me know if it helps. And yes, the point is to generate the models' files right into Visual Studio.

**Comment by HarveyWilliams** [comment]
Thanks I didn't spot that section. I got it working after following the information posted there.
