### ISSUE TITLE
IgnorePropertyType on composed property also ignores on the composition

### ISSUE THREAD

**Issue by quiznaut** [zpqrtbnk/Zbu.ModelsBuilder#132]
I added the IgnorePropertyType attribute to a class.  The specified property was coming from a composition.  When I generate models, the property no longer appears in the class, but it also no longer appears in the composition.

I expected the property to be ignored only in the class on which I specified the attribute. Please let me know if I had the wrong expectation.

**Comment by zpqrtbnk** [comment]
This is an old issue... are you still there? ;-)
Sorry for the crazy delay - triaging the backlog now.

Problem is, you cannot really ignore a property type at class level, if the property comes from a composition. The composition is represented by an interface, which is implemented by the class, which therefore *has* to have the property.

Going to close this issue, if you don't mind - if you do, tell me!
