### ISSUE TITLE
ModelsBuilder Command Line

### ISSUE THREAD

**Issue by NunoInacio** [zpqrtbnk/Zbu.ModelsBuilder#149]
I'm currently using ModelsBuilder API to generate my .cs files for the Models and it works like a charm! I've followed the recomended setup for it [here](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/wiki/Builder-Modes#api-models) but now i would like to take this to the next level which for me is to run the Custom Tool related with the Builder.cs class on a VS Pre Build event.

First of all, is that possible?

I've noticed that there is a ModelsBuilder Console application and I already tried to use it directly on the Command Window but with no success.

My Umbraco instalation is 7.6.1 and VS Enterprise 2015.

I've already posted on Our [link](https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/86023-modelsbuilder-command-line)

**Comment by zpqrtbnk** [comment]
In a pre-build event, you cannot use the VSIX Custom Tool - you would indeed need to use the console tool. As far as I can remember, it worked. What problems are you facing.

Or ... *were* you facing ... I realize this issue is quite old - trying to catchup.
