### ISSUE TITLE
Request - Is it possible to generate a model for dictionary items?

### ISSUE THREAD

**Issue by photogsy** [zpqrtbnk/Zbu.ModelsBuilder#156]
We have a couple of multi-lingual sites, which use separate home nodes (and trees), each with different culture set. Currently we have to use `Umbraco.GetDictionaryValue("magic-string")` to get dictionary values - would it be possible for ModelBuilder to generate a strongly typed class for these instead?

**Comment by zpqrtbnk** [comment]
That would be a feature request - and currently ModelsBuilder is really for content items, so that would even be another project entirely. An interesting one ;-) but out of scope here.
