### ISSUE TITLE
Feature Request - Include a factory that takes a document type alias string and returns the correctly newed model

### ISSUE THREAD

**Issue by JohnBergman** [zpqrtbnk/Zbu.ModelsBuilder#159]
Title says it all, but basically, in the current implementation, you have to pre-know what document type you are working with, making it so you need to add your own series of switch/case statements (or whatever) to decide the node's alias and new up the right object.

This would be particularly useful when you have extended to generated classes to include things like interfaces and act on them accordingly.

**Comment by zpqrtbnk** [comment]
Not sure I follow you - and sorry to reply so late ;-( 

I am going to close the issue - but if you are still interested / impacted and want to elaborate, can you reopen/comment/whatever?
