### ISSUE TITLE
Umbraco 7.3.8 and Models Builder - help

### ISSUE THREAD

**Issue by pedroadaodev** [zpqrtbnk/Zbu.ModelsBuilder#167]
Hi,

I'm trying to get ModelsBuilder with Umbraco 7.3.8.

These are my steps
1 - reinstal nuget packge Umbraco 7.3.8
2- Install-Package Zbu.ModelsBuilder -Version 2.1.5
3- Install-Package Zbu.ModelsBuilder.AspNet -Version 2.1.5 (this was missing)

Now I can see the developer dashboard (step 3 was missing)

Dashboard information:
Zbu.ModelsBuilder
Umbraco
Config: +EnableApi +EnablePublishedContentModelsFactory
Config.ModelsNameSpace: ""
Config.StaticMixinGetters: disabled

4- installed the VS 2017 extension
5- Configured the VS extension with my umbraco credentials
6- Run custom tool generates error
```
UmbracoModelsBuilder: UmbracoModelsBuilder failed to generate code: Exception: Response status code does not indicate success (NotFound)

UmbracoModelsBuilder:    at Umbraco.ModelsBuilder.Api.ApiClient.EnsureSuccess(HttpResponseMessage result)
```

In my webconfig
```
    <add key="Umbraco.ModelsBuilder.Enable" value="true" />
    <add key="Umbraco.ModelsBuilder.ModelsMode" value="nothing" />
    <add key="Umbraco.ModelsBuilder.EnableApi" value="true" />
```

What am I doing wrong? :)

Thanks,
Pedro

**Comment by zpqrtbnk** [comment]
You are using version 2 of ModelsBuilder, when it still was "Zbu.ModelsBuilder", with the version 3 settings for "Umbraco.ModelsBuilder" - not sure why you are using version 2 (version 7.3 is old-ish) but you can find the appropriate settings in the [documentation](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/wiki).

(now, I realize I'm super late answering that question - sorry about it)
