### ISSUE TITLE
Can't modify custom tool in file property in VS 2017

### ISSUE THREAD

**Issue by halfer53** [zpqrtbnk/Zbu.ModelsBuilder#168]
I am trying to modify the custom tool property, however, the Custom Tool section is greyed and can 't be modified. 

![image](https://user-images.githubusercontent.com/5958912/40582431-ee4caed2-61ca-11e8-9fa0-72ae88ca9e2a.png)

**Comment by zpqrtbnk** [comment]
hey - sorry for delay - is this still a question?

what is the type of the file, ie is it a true c# file with action set to compile?

**Comment by halfer53** [comment]
Never mind, that was like a year ago. I think I ended up disabling the Model intelligence.
