### ISSUE TITLE
Remove comments that reference IDs

### ISSUE THREAD

**Issue by ronaldbarendse** [zpqrtbnk/Zbu.ModelsBuilder#173]
Currently, the IDs of content types are added as comments to the generated code. When using AppData mode (or API, whatever writes to code to disk), the generated source can therefore change if the local ID is different (e.g. when restored from an Umbraco Cloud site):
https://github.com/zpqrtbnk/Zbu.ModelsBuilder/blob/4e8ecdb940275c28eab3afe825da899dba9cf4b6/Umbraco.ModelsBuilder/Building/CodeDomBuilder.cs#L46
https://github.com/zpqrtbnk/Zbu.ModelsBuilder/blob/4e8ecdb940275c28eab3afe825da899dba9cf4b6/Umbraco.ModelsBuilder/Building/CodeDomBuilder.cs#L84

I don't know if the ID should be changed to the GUID or just removed, but both options will result in an identical generated file...

It's not a big deal, but reverting these changes just recreates it (on saving the content type) and committing it would result in other developers having the same problem (and add unnecessary commits/changes).

**Comment by zpqrtbnk** [comment]
Totally makes sense - should be the GUID, most probably.

**Comment by ronaldbarendse** [comment]
Take your pick: just remove the IDs or replace them with GUIDs 👍 

PS While running the tests, not all were successful... After checking the current master branch, it seems this is because the namespaces are not correctly cleaned/simplified. The tests do however give the same (failed) results as before 😇

**Comment by zpqrtbnk** [comment]
Have completely removed the IDs.
Also, tests are fixed.
Now committed, will show in next release (don't ask when ;-)
