### ISSUE TITLE
Give a hint of which Modes are available when you set it wrong

### ISSUE THREAD

**Issue by PeteDuncanson** [zpqrtbnk/Zbu.ModelsBuilder#176]
![image](https://user-images.githubusercontent.com/1674590/45032199-0e129480-b049-11e8-9fc6-4fef2c21e53a.png)

I mis-typed the DLL setting in all upper case, in the error message it warns me about using the right case, would be even better if it told me what the options are for completeness.

**Comment by SimonHartfield** [comment]
https://github.com/zpqrtbnk/Zbu.ModelsBuilder/pull/178

**Comment by zpqrtbnk** [comment]
woot! no haven't, and I might even have hard-coded the values ;-) nice work, merging!
