### ISSUE TITLE
ModelsBuilder Options Not Updated Unless Models Build UI is Opened

### ISSUE THREAD

**Issue by ProNotion** [zpqrtbnk/Zbu.ModelsBuilder#182]
I have many projects using ModelsBuilder and when I switch between them and attempt to run the tool it fails the first time until I open the ModelsBuilder Options UI where it shows the previous sites url, username and password. After closing the dialog (without any changes) and reopening it, the details appear to then be corrected and loaded from the solutions <ProjectName>.UmbracoModelsBuilder.user file.

**Comment by Alkaersig** [comment]
Yeah we are having this issue as well. We are using the Custom Tool for a lot of our projects, but when changing project the settings are not loaded.

**Comment by zpqrtbnk** [comment]
odd - going to look into this

just to be sure, "multiple projects" = real different projects within the same VS solution, or different solutions?

**Comment by ProNotion** [comment]
Different solutions. E.g. Close one solution then open the next and the previous solution settings are still in place when you first try to connect or open the dialogue.

**Comment by zpqrtbnk** [comment]
thanks - would be settings not being updated when opening / closing solutions - looking into it

**Comment by Alkaersig** [comment]
Yeah same thing here. Does not matter if i open/close solutions using Team Explorer (Git) or the File menu, the setting is not updated until either closing VS or opening the options menu.

**Comment by ProNotion** [comment]
I don't know for sure from a technical standpoint but my guess is that the tool is an extension of Visual Studio (the host) itself so a change of context in regards to the solution does not make much if any difference to the host. This theory is supported by the fact that you can access the extension settings even with no solution open in Visual Studio.

**Comment by zpqrtbnk** [comment]
Done in source. See core task [4880](https://github.com/umbraco/Umbraco-CMS/issues/4880) for release.
