### ISSUE TITLE
CustomTool should support multiple server versions

### ISSUE THREAD

**Issue by zpqrtbnk** [zpqrtbnk/Zbu.ModelsBuilder#190]
At the moment, the custom tool only supports a very narrow set of server versions. That is, different custom tools are required to work with different versions of Umbraco. Especially, the v8 custom tool is not going to support v7. This is going to create difficult situations.

The tool should be enhanced to support any target version really.

**Comment by FransdeJong** [comment]
Maybe you could add a dropdown in the modelsbuilder options? That way you can switch per project?
Makes it easier than autodetecting right?

**Comment by zpqrtbnk** [comment]
Have pushed version 8.0.3 of the extension that *should* work with v7 - anyone want to test?

**Comment by rosswebediaglasgow** [comment]
Looks good, thanks!

**Comment by FransdeJong** [comment]
Works like a charm! Thanks!

**Comment by zpqrtbnk** [comment]
great - so the tool works with v7 ... and once v8 8.0.1 is released, it should work with v8 too

**Comment by Alkaersig** [comment]
Great work! Thanks. Had mine autoupdate to 8.0.2 and had to search old download folders to find a working version. 8.0.3 fixed it 🎉 👍
