### ISSUE TITLE
Warning when uploading VSIX

### ISSUE THREAD

**Issue by zpqrtbnk** [zpqrtbnk/Zbu.ModelsBuilder#191]
When uploading the VSIX extension, the Visual Studio Marketplace warns:
> (Umbraco ModelsBuilder Custom Tool) The package (Umbraco.ModelsBuilder.CustomTool.UmbracoModelsBuilder) class in any VSIX supporting Visual Studio 2015 or later should derive from AsyncPackage instead of Package. Read more about using AsyncPackage here: https://aka.ms/asyncpackage.

So... should probably do something about it

**Comment by FransdeJong** [comment]
I added more info in issue https://github.com/zpqrtbnk/Zbu.ModelsBuilder/issues/199
It seems that this issue is not entirely related.

**Comment by zpqrtbnk** [comment]
Going to group that one with #204 - please see updates there (there's a new VSIX to test) and also report there. Thanks!

**Comment by FransdeJong** [comment]
I tested it in VS2019 and it seems to work without any issues now

**Comment by zpqrtbnk** [comment]
Warning is gone with 8.0.5 - issue closed.
