### ISSUE TITLE
Update loading indicator in dashboard

### ISSUE THREAD

**Issue by bjarnef** [zpqrtbnk/Zbu.ModelsBuilder#194]
It would be great to replace the loading indicator in ModelsBuilder dashboard, which is shown when generating models.
https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Web.UI/App_Plugins/ModelsBuilder/modelsbuilder.html#L30-L32

```
<div class="umb-loader-wrapper" ng-show="vm.generating">
       <div class="umb-loader"></div>
</div>
```

Similar to this in NuCache dashboard using `umb-load-indicator`:
https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Web.UI.Client/src/views/dashboard/settings/nucache.html#L3-L5

```
<div ng-show="vm.loading || vm.working" style="background: rgba(255, 255, 255, 0.60); position: absolute; left: 0; right: 0; top: 0; bottom: 0;">
        <umb-load-indicator></umb-load-indicator>
</div>
```

The inline styling is an overlay while loading. Maybe @nielslyngsoe has an idea to a name of this class maybe `umb-load-indicator-wrapper`?

**Comment by bjarnef** [comment]
Note that the `umb-loader` + `umb-loader-wrapper` are used a few places, but mainly at tree nodes.
https://github.com/umbraco/Umbraco-CMS/search?q=umb-loader&unscoped_q=umb-loader

I think is would make sense to put this in another component e.g. `umb-loader` so the markup is only maintained from a single file. Furthermore it is wrapper `umb-loader-wrapper` is missing, which it was original in Umbraco, I got some annoying horizontal scrollbar on/off while `umb-loader` was animating.

**Comment by ronaldbarendse** [comment]
And also make sure the loader is contained within the box:

![Loader outside box](https://user-images.githubusercontent.com/1051287/61049489-e6b4f280-a3e4-11e9-9b4a-dcfbd65956f5.png)

**Comment by zpqrtbnk** [comment]
Thanks @ronaldbarendse - @bjarnef any chance you can have a look at this, so I can merge in an upcoming release?

**Comment by zpqrtbnk** [comment]
Core umb-loader component now works, using it...

**Comment by zpqrtbnk** [comment]
Good
