### ISSUE TITLE
Model name suffix

### ISSUE THREAD

**Issue by mmadukah** [zpqrtbnk/Zbu.ModelsBuilder#217]
Is there any chance of adding functionality to add a suffix to the generated models as the generated names tend to clash with our POCO domain model names?

**Comment by mmadukah** [comment]
# #213

**Comment by zpqrtbnk** [comment]
Yes, and directly related to #213 which is about prefix. Adding to backlog too.

**Comment by zpqrtbnk** [comment]
Closing as duplicate of #213 which is in-progress.
