### ISSUE TITLE
Web.Config change Kills IIS Express

### ISSUE THREAD

**Issue by croban** [zpqrtbnk/Zbu.ModelsBuilder#218]
Wenn started in LiveAppData model, by changing web.config cause iis express stops to work

**Comment by zpqrtbnk** [comment]
Hi!

What do you mean "by changing web.config"? So the site is running, with models mode being "LiveAppData", and all other settings being normal, and then... can you elaborate on what you do and what happens?

**Comment by croban** [comment]
If model builder is on and if you even touch/save web.config or if you build application,
IIS Express crashes and I have to start iis express again (strg+f5 or f5) and again.

**Comment by zpqrtbnk** [comment]
have you tried with Models Builder off? Rebuilding the app in Visual Studio *does* restart the app, IIRC

anything in logs?

**Comment by croban** [comment]
yes i have tried, if the model builder is disabled, i don't have this problem but than model factory also does not work. 
My tough is to disable model builder and explicitly enable factory, maybe this will help. 
But that I have to try out.

**Comment by croban** [comment]
I think that I have found problem:
Changing ModelMode to Nothing solves this problem (it was AppData). 
Changing web.config and building of course restarts app but not does not kill IIS Express process anymore :).

**Comment by zpqrtbnk** [comment]
Glad it's ok for you now. Want to close the issue?

Though... I still don't understand why AppData would cause IIS Express to restart - but IIS Express is weird sometimes.
