### ISSUE TITLE
ModelsBuilder API Generates first IPublishedElement then never finishes

### ISSUE THREAD

**Issue by naepalm** [zpqrtbnk/Zbu.ModelsBuilder#237]
Hey, I'm running into a really strange issue on a new website that runs on Umbraco Cloud. We have a Core project for the class library and a Web project for the front per the Cloud instructions. I have the ModelsBuilder API installed and I'm attempting to generate the models into the Core project. It starts, generates the first IPublishedElement (SeoNavigation.generated.cs), but doesn't generate any more, never finishes, and also never throws an error. I've waited for over an 30 minutes and it just sits there, forcing me to terminate the process on my computer to close it.

I've attempted rebuilding the solution, deleting the files (including my base builder I have the custom tool set to) and regenerating them fresh, and I've checked all my settings. Since it starts generating them, and doesn't throw an error, I'm not exactly sure if I'm doing something wrong or if it's failing under the hood and never throwing the error to the front.

**Tools**
Umbraco v8.6.1
Umbraco.ModelsBuilder v8.1.0
Umbraco.ModelsBuilder.Api v8.1.0
Visual Studio Extension v.8.0.5.190617001

**Web.Config**
```
<add key="Umbraco.ModelsBuilder.Enable" value="true" />
<add key="Umbraco.ModelsBuilder.ModelsMode" value="Nothing" />
<add key="Umbraco.ModelsBuilder.EnableApi" value="true" />
<add key="Umbraco.ModelsBuilder.LanguageVersion" value="CSharp6" />
```

**Notes**
* Login is set properly in options and it appears to be able to successfully connect
* Debug is set to true

Any ideas?

**Comment by andyfelton2** [comment]
Hi - 

I've got the same problem with a local project generates the first file then spins until I kill it. 

Any thoughts?

**Comment by zpqrtbnk** [comment]
Weird. I remember it happening to me long time ago, generating the first file and then hanging. Thought it was fixed. Let me try to remember.

**Comment by zpqrtbnk** [comment]
possibly related to #210 ? Are you using the [custom tool](https://marketplace.visualstudio.com/items?itemName=ZpqrtBnk.UmbracoModelsBuilderCustomTool) or the [extension](https://marketplace.visualstudio.com/items?itemName=ZpqrtBnk.UmbracoModelsBuilderExtension)?

**Comment by naepalm** [comment]
@zpqrtbnk Ah-hah! I'm using the Custom Tool; it's what I've had for ages and I haven't thought to swap it because it's "just worked"! I'll update to the extension and see if that resolves my problem.

**Comment by andyfelton2** [comment]
@zpqrtbnk Ditto me as well - thanks I'll take a look!

**Comment by zpqrtbnk** [comment]
Don't mention Ditto.

**Comment by naepalm** [comment]
Hey @zpqrtbnk, no luck... when I switch to the Extension instead of the custom tool and set my builder file to have **UmbracoModelsBuilder** as the custom tool, it simply does nothing. No logs, no errors, no output. Just... nothing.

I did check:

* Login information is correct
* Login URL is set to local and I can connect to it
* Debug is set to true
* I can see the API models are on in the backoffice after installing the UI Nuget Package

**Comment by zpqrtbnk** [comment]
The extension does not work with a "custom tool", you may want to read [this blog post](https://www.zpqrtbnk.net/posts/models-builder-extension/) for details.

**Comment by naepalm** [comment]
@zpqrtbnk Ah-hah! The [VS extension page](https://marketplace.visualstudio.com/items?itemName=ZpqrtBnk.UmbracoModelsBuilderExtension) points to this wiki for setup documentation, which still references using the Custom Tool on [this page](https://github.com/OurModelsBuilder/Our.ModelsBuilder/wiki/Builder-Modes#api-models) so that was what I thought I should do. I'll read the blog post and implement it that way :)

**Comment by naepalm** [comment]
@zpqrtbnk The blog post worked like a charm. I'm golden; thank you so much for the help!
