### ISSUE TITLE
Runtime error after upgrading: Could not load file or assembly 'System.Collections.Immutable'

### ISSUE THREAD

**Issue by danlister** [zpqrtbnk/Zbu.ModelsBuilder#25]
After updating `Zbu.ModelsBuilder`, `Zbu.ModelsBuilder.AspNet` and the Visual Studio Extension, I receive the following exception after successfully building an application:

    Could not load file or assembly 'System.Collections.Immutable, Version=1.1.22.0' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I've upgrade the following packages and Visual Studio extensions:

- `Zbu.ModelsBuilder` to 2.0.2-final
- `Zbu.ModelsBuilder.AspNet` to 2.0.2-final
- Visual Studio Extension to 2.0.2.31

I noticed 2.0.2-final is dependant on [`Microsoft.Bcl.Immutable`](https://www.nuget.org/packages/Microsoft.Bcl.Immutable/) but the package has been unlisted from nuget.org. After looking around, it appears to have been moved to [`System.Collections.Immutable`](https://www.nuget.org/packages/System.Collections.Immutable/).

I also noticed that after upgrading, my System.Collections.Immutable reference went from Microsoft.Bcl.Immutable.1.1.22-beta to Microsoft.Bcl.Immutable.1.1.20-beta. 

Would updating the package reference help fix this issue?

**Comment by zpqrtbnk** [comment]
2.0.3 will update dependencies to fix that issue.
