### ISSUE TITLE
Error: Already referencing a newer version of 'Microsoft.Bcl.Immutable'.

### ISSUE THREAD

**Issue by MrMattTaylor** [zpqrtbnk/Zbu.ModelsBuilder#29]
Installed I have:

Zbu.ModelsBuilder to 2.0.0-final (Prerelease)
Zbu.ModelsBuilder.AspNet to 2.0.0-final (Prerelease)
Visual Studio Extension for Windows Lib... v1.0.9200
ZpqrtBnk Umbraco ModelsBuilder Custom Tool 2.0.2.31

I'm trying to update the nuget Zbu.ModelsBuilder packages to 2.0.2 but I just get the following error.
Error: Already referencing a newer version of 'Microsoft.Bcl.Immutable'.

My installed Microsoft.Bcl.Immutable package version is 1.1.22-beta.

![immutable](https://cloud.githubusercontent.com/assets/6153443/5652575/bf853686-96a9-11e4-8eba-c4d8e8bf136d.jpg)

**Comment by zpqrtbnk** [comment]
Will try to upload an updated release sometime this week.

**Comment by MrMattTaylor** [comment]
Thanks. I'm using it with the Hybrid Framework and I like to use it but if I can't update it and hopefully get the Custom Tool to run I'll have to remove it. :-(
