### ISSUE TITLE
Debugging Version Conflict 0.0.0.0 issue

### ISSUE THREAD

**Issue by BluefinDigital** [zpqrtbnk/Zbu.ModelsBuilder#32]
Hi Stephan,

Your ModelsBuilder has been working brilliantly for me for the past few weeks and its an awesome new addition to the Umbraco dev toolkit.  Randomly yesterday however, it started failing with the below message:

ZbuModelsBuilder: Starting 23/01/2015 09:19:14.
ZbuModelsBuilder: ZbuModelsBuilder failed to generate code: Exception: Response status code does not indicate success (Forbidden)
"API version conflict: client version (0.0.0.0) is not compatible with server version(2.0.3.34)."
ZbuModelsBuilder:    at Zbu.ModelsBuilder.AspNet.ModelsBuilderApi.EnsureSuccess(HttpResponseMessage result)
   at Zbu.ModelsBuilder.AspNet.ModelsBuilderApi.ValidateClientVersion()
   at Zbu.ModelsBuilder.CustomTool.CustomTool.ZbuModelsBuilder.GenerateRaw(String wszInputFilePath, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, String& errMsg)

I looked back over my commits since it failed and I cannot find any reason why this has happened (no new nuget packages, no changes to the config or anything).  Anyway I noticed there was an new version (2.0.3) so I updated both the main package and the site integration tool via Nuget.  I restarted VS2012 however I continue to get the above API version conflict message.  How do I debug this or manually set the client version number?

Thanks, keep up the great work!

**Comment by zpqrtbnk** [comment]
Hey. The error message says "... is not compatible with server version (2.0.3.34)" which means that version 2.0.3-final is properly installed on the server (website) site. The error message says "client version (0.0.0.0) is not..." which is something I don't understand at the moment.

You're not the first one to report that issue. But it makes no sense ;-) Somehow it looks like the extension is corrupted and sends garbage to the site. Any chance you can: open VS2012, uninstall the VSIX extension, close VS2012, re-install the VSIX extension by double-clicking the VSIX file (and making sure you do install for VS2012 and not only VS2013), re-open VS2012 and try again?

**Comment by BluefinDigital** [comment]
No joy Stephan - still get the same error.  I messed around with the tool config, and confirmed if the password is blank, I correctly get a *Exception: Invalid configuration*. And with an incorrect password, I correctly get a *Exception: Response status code does not indicate success (Unauthorized)*.

With the correct password it is odd as *Response status code does not indicate success (Forbidden)* would suggest a 403 http error, but maybe that is by design as it is receiving bad config.

As a workaround I was going to try using the dashboard tool, but I don't see a button or anything I can action, is there something I need to do to enable this?

Config: +EnableApi +EnablePublishedContentModelsFactory
Config.ModelsNameSpace: ""

**Comment by zpqrtbnk** [comment]
The 403 / forbidden error is by design indeed. Client is forbidden to talk to the server because its version is not compatible. Now why is it reporting version "0.0.0.0"?! With the latest 2.0.3-final?! Must debug.

As to how to enable the button... you want to look at [that wiki doc page](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/wiki/SiteIntegrationConfiguration) for more details.

**Comment by BluefinDigital** [comment]
Thanks - I RTFM'd and got the dashboard control working by enabling Zbu.ModelsBuilder.EnableAppCodeModels.  That is generating all the models fine so it seems indeed just to do with the VS extension.

Yes I can confirm the latest version custom tool is installed in VS2013 (2.0.3.34)

**Comment by zpqrtbnk** [comment]
Just to make sure: you seem to mention VS2012 & VS2013... the proper tool is installed on the proper VS, right? (and don't ask me how much time I've wasted debugging the wrong tool on the wrong VS...)

**Comment by BluefinDigital** [comment]
Sorry, that was a typo, I only use VS2012.  I installed the tool from here https://visualstudiogallery.msdn.microsoft.com/3ac3afd4-09db-4c4f-89aa-6ce9e8e7c046

It says it supports both 2012 and 2013 - how do ensure I have installed the proper version?

**Comment by zpqrtbnk** [comment]
Supports both - it's just that when you install, if VS2012 & VS2013, the installer will display checkboxes for you to pick which VS versions you want to install to. If you're running only VS2012 then it should be fine.

**Comment by zpqrtbnk** [comment]
Looks like there are issues with JSON serialization of System.Version objects, depending on the version of the serializer, which is difficult to control. Will try to make sure these versions are passed as strings.
