### ISSUE TITLE
zbu base models?

### ISSUE THREAD

**Issue by jesperordrup** [zpqrtbnk/Zbu.ModelsBuilder#35]
Example: I have 5 doctypes. All use the same doc type composition.

Is it possible to iterate over a base class and do stuff like:

foreach (baseclass item in items.Where(wow => wow.docTypeCompProperty.Equals("cool")) {

}

**Comment by zpqrtbnk** [comment]
If they all use the same _composition_ BaseType then the builder should generate an interface named IBaseType and each of your doctypes should implement that interface, and so you should be able to do something along:
```
foreach (var item in items.Cast<IBaseType>().Where(x => x.BaseProperty == "cool"))
{...}
```
So in _theory_ it should work OOTB unless I've done something wrong.

**Comment by jesperordrup** [comment]
Which is kind of exactly what I was looking for. Thank you zpqrtbnk
