### ISSUE TITLE
Ignoring properties on composition types

### ISSUE THREAD

**Issue by naepalm** [zpqrtbnk/Zbu.ModelsBuilder#39]
When ignoring a property on a composition type, the interface still generates.

**Comment by zpqrtbnk** [comment]
Would be... if 
```
[IgnorePropertyType("something")]
public partial class SomeType { ... }
```
Then property ```Something``` would not be generate on the type, but interface ```ISomeType``` would still declare it, which is a bug. Fixed: when the property is ignored on the type, it's ignored on the interface.

Note that it has to be ignored on the *type*. Attributes such as ```IgnorePropertyType``` do not work on partial interfaces.
