### ISSUE TITLE
Do I have to use IgnorePropertyType instead of ImplementPropertyType to implement my own logic?

### ISSUE THREAD

**Issue by highstone** [zpqrtbnk/Zbu.ModelsBuilder#43]
I have my generated models living in the folder \Models\Generated. In there I have my ContentModelBuilder.cs setup to use the custom tool ZbuModelsBuilder, and set the Namespace to MyProject.Umbraco.Web.Models. So far so good.

However, I have an issue when I want to override certain properties in partial classes as it seems that I have to put all the attribute decorations in my ContentModelBuilder.cs class. To avoid having the property defined in the Xyz.generated.cs and Xyz.partial.cs I need to first ignore the property in the ContentModelBuilder.cs and then implement it in the Xyz.partial cs.
I expected that when I could decorate the properties I want to imlement myself with the [ImplementPropertyType] attributes in my Xyz.partial.cs class. And probably also the [RenameContentType] attribute, but I can live with this.

Note that to avoid that the naming of my contentmodels collides with other models or classes, I suffix all my contentmodels with ...ContentModel, hence the RenameContentType.
```
[ContentModelBuilder.cs]

[assembly: RenameContentType("Xyz", "XyzContentModel")]
namespace MyProject.Umbraco.Web.Models
{
    [IgnorePropertyType("whatever")] //<-- I have to put this here in the ContentModelBuilder
    public partial class XyzContentModel { }
}
```
```
[Xyz.partial.cs]

namespace MyProject.Umbraco.Web.Models
{
    public partial class XyzContentModel
    {
        [ImplementPropertyType("whatever")] //<-- As this is not enough...?
        public RJP.MultiUrlPicker.Models.Link Whatever
        {
            get 
            { 
                return this.GetPropertyValue<string>("whatever");
            }
        }
    }
}
```
Is this behavior as intended, or am I just missing something obvious?

**Comment by zpqrtbnk** [comment]
The tool parses all the files that live in the same directory that already contains the "custom tool" file, ie ContentModelBuilder.cs in your case, if I understand correctly. So this is where you want your partial class to be, too. So Whatever.generated.cs and Whatever.partial.cs end up in the same directory.

And then ```[ImplementPropertyType("whatever")]``` on the property in the partial ''should'' be enough.

Either you partial files are not in the right place, and therefore not parsed, or there's a bug somewhere.

**Comment by highstone** [comment]
Ah, then that was the obvious thing I'm missing ;-)
I had my generated models in Models\Generated, the partial implemented models in \Models

Thanks for your prompt response!

**Comment by zpqrtbnk** [comment]
Fine
