### ISSUE TITLE
Question regarding 6 and 7

### ISSUE THREAD

**Issue by qz2rg4** [zpqrtbnk/Zbu.ModelsBuilder#45]
Hi 

I was under the impression that umbraco v6 and v7 are the same except for the new backend.

So is it possible that the models builder will work for Visual Studio?

Thanks

**Comment by zpqrtbnk** [comment]
There are minor differences in v6 and v7 which means that the distributed build (on NuGet) will work on v7 but not on v6 - that being said, the project can build on top of v6, you need to put to right libs in the right directory, and I think there's a conditional define to set too. And then yes it works (been using it on a v6 project). Only, I'd rather not *maintain* it for v6 & distribute binaries.

**Comment by qz2rg4** [comment]
Thanks
