### ISSUE TITLE
More that one type want to be a model for content type "testAlias"

### ISSUE THREAD

**Issue by villian** [zpqrtbnk/Zbu.ModelsBuilder#47]
HI,

Great idea and great package !!! 
We have such exception after generation of models:

 System.InvalidOperationException: More that one type want to be a model for content type AreaSectionPage.

Thanks

**Comment by zpqrtbnk** [comment]
This means that once the generated models have been compiled, and the website boots, and the models factory tries to locate models, it finds more than one class type that pretends to be a model for a given content type.

The models builder will initialize the factory with every class types that inherit from PublishedContentModel, then the factory will match those types to content types by using the class type name, or the PublishedContentModelAttribute if any.

Can you look at your solution's code (generated & non-generated) and see if there's no duplicate in there?

**Comment by villian** [comment]
Hi Stephan,

We checked, everything is fine, no duplicate in there.
We are using uSync for tracking db changes, can be problem in therer ? 

Thanks

**Comment by villian** [comment]
Hi Stephan,

Thank you very much for help, problem was because we renamed 'Zbu.ModelsBuilder.ModelsNamespace', and forgotten to remove old dll.

Thank you again !!!
