### ISSUE TITLE
Implement the constructor in the not generated model

### ISSUE THREAD

**Issue by teusch** [zpqrtbnk/Zbu.ModelsBuilder#56]
I want to ad an object to the model object and I'm now doing this by taking out the constructor in the generated class and implementing it in my own partial (see code).
This works but of course as soon as I generate, the constructor appears in the generated file.
Is there a way to let the generator know the constructor is in the other file?

Regards
Teus

```c#
namespace Umbraco.Extensions.Models.Generated
{
    public partial class Production
    {
        public readonly Project FoundProject;

        public Productie(IPublishedContent content)
            : base(content)
        {
            FoundProject = iTheatreData.DAL.GetProjectByName(this.name);
        }
etc
```

**Comment by zpqrtbnk** [comment]
Got it, see what you want. We should detect that you are already implementing a constructor with the proper signature in your own partial class, and we should not generate a new constructor. Working on it.

**Comment by zpqrtbnk** [comment]
Implemented.

**Comment by teusch** [comment]
Thanks !
