### ISSUE TITLE
Cannot install extension in Visual Studio 2015 (RC)

### ISSUE THREAD

**Issue by vnbaaij** [zpqrtbnk/Zbu.ModelsBuilder#58]
I would like to use the vsix extension from vs2015. The current vsix doesn't recognize that version

**Comment by zpqrtbnk** [comment]
Next beta of 2.1.3 will declare it supports VS15.
Cannot test as I don't have VS15 immediately available.
When it is out, let me know if it works.

**Comment by zpqrtbnk** [comment]
Out now, you can get the extension from the [release](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/releases/tag/2.1.3-beta009) page. Let me know if it works.

**Comment by zpqrtbnk** [comment]
Should work in 2.1.3 but cannot test. Moving to 2.2.0 and keeping the issue open.

**Comment by zpqrtbnk** [comment]
I have installed VS15, will test, moving to 2.1.4.

**Comment by zpqrtbnk** [comment]
Tested OK, 2.1.4 installs and runs on VS2015
