### ISSUE TITLE
Is it possible to use global:: if you generate the models?

### ISSUE THREAD

**Issue by calaa** [zpqrtbnk/Zbu.ModelsBuilder#59]
If it generates something like

```csharp
public Umbraco.Web.Models.ImageCropDataSet Cropper
{
}
```

And my Namespaces contains following: Opten.xyz**.Umbraco.Web.**Models

I get an error:

The type or namespace name 'Web' does not exist in the namespace xyz.Umbraco (are you missing an assembly reference)?

So we have do add manually global:: everytime we rebuild it.

```csharp
public global::Umbraco.Web.Models.ImageCropDataSet Cropper
{
}
```

**Comment by zpqrtbnk** [comment]
Guess your namespace must contains something like `Whatever.Umbraco.Something` and then when the compiler sees `Umbraco.Web...` it does not know whether `Umbraco` is the global one, or yours.

We probably want to `global::` all the types in the generated code to make sure there cannot be any confusion. Looking into it.

**Comment by calaa** [comment]
Yep exactly that's the "problem". Sometimes we have .Umbraco. in our namespaces.

If it makes sense to implement that, I would really appreciate it.

**Comment by zpqrtbnk** [comment]
Notes to self: two solutions, (1) a config option to use `global::MyNamespace.MyType` style for everything or (2) find a way to figure out whether a type we're outputting is ambiguous or not.

**Comment by zpqrtbnk** [comment]
Note: going with option (2) and using Roslyn to figure out whether a type symbol is ambiguous or not.

**Comment by zpqrtbnk** [comment]
Done. What we do is prepare a code fragment containing all the `using` statements that go into models file, and the `namespace` statement corresponding to the models, and then Roslyn compiles that fragment and provides us with a semantic model that we can use to lookup symbols, and figure out whether they are ambiguous. When a symbol is ambiguous, we use the full `global::Path.To.Symbol` notation.
