### ISSUE TITLE
Cannot install VSIX with VS2015

### ISSUE THREAD

**Issue by zpqrtbnk** [zpqrtbnk/Zbu.ModelsBuilder#60]
I have installed VS2015 RTM. Whenever I double-click Zbu.ModelsBuilder VSIX file, nothing happens. An exception is logged in the event logged about some UnauthorizedAccess exception being thrown when trying to open the VSIX installer log.

**Comment by zpqrtbnk** [comment]
Manually launch the VSIXinstaller.exe from \Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE - same issue unless I'm administrator and then it works. From the help menu that opens, we see that VSIX installer wants to create log files in %TEMP%.

Which is \Users\Stéphane\... for me... Oh... now there's a \Users\St%C3%A9phane directory too, that was created when VS2015 was installed, and sure enough... the install logs are there. Give my user full permission on that directory...

... and now when I double-click the VSIX file, it works. So the issue is with VSIX installer that has an issue understanding the accent in my user directory. Damn damn damn.

**Comment by zpqrtbnk** [comment]
VSIX installer does something similar to `new Uri(Path.GetTempPath())` and that creates an invalid path.
Write to: Path.Combine(Path.GetTempPath(), "test.txt") = works.
Write to: new Uri(new Uri(Path.GetTempPath()), "test.txt").AbsolutePath = fails.

**Comment by zpqrtbnk** [comment]
OK, that has to be a bug within the VSIX installer. What's strange is that the code does not seem to have change. Reported to MS...

**Comment by zpqrtbnk** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/1576068

**Comment by ryanlewis** [comment]
FWIW, works for me and my standard ASCII home directory

**Comment by zpqrtbnk** [comment]
MS reported "_We have fixed this bug and it will be available in our next update._" on Connect on 08/08.
Closing.
