### ISSUE TITLE
Error after nuget upgrade

### ISSUE THREAD

**Issue by qz2rg4** [zpqrtbnk/Zbu.ModelsBuilder#61]
Hi 

After the nuget upgrade I'm getting the following error Umbraco 7.2.8

Could not load control: '/UserControls/Zbu/ModelsBuilder/BuildModels.ascx'. 
Error message: System.Web.HttpCompileException (0x80004005): c:\inetpub\wwwroot\uGamco\usercontrols\Zbu\ModelsBuilder\BuildModels.ascx(22): error CS0117: 'Zbu.ModelsBuilder.Configuration.Config' does not contain a definition for 'MixinPropertiesGeneratorMode' at System.Web.Compilation.AssemblyBuilder.Compile() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at Umbraco.Web.UI.Umbraco.Dashboard.UserControlProxy.OnInit(EventArgs e)

**Comment by zpqrtbnk** [comment]
Confirmed. Fixing.

**Comment by thilemann** [comment]
Any updates on this bug? I'm having the exact same issue.

**Comment by zpqrtbnk** [comment]
Is fixed, now I need to release. Was away, will do asap.

**Comment by thilemann** [comment]
Thanks! Looking forward to use it again!
