### ISSUE TITLE
Installation error in Windows 10 (workaround)

### ISSUE THREAD

**Issue by ralphvanvugt** [zpqrtbnk/Zbu.ModelsBuilder#62]
The vsix file cannot be installed on systems using Windows 10. Installation fails because the required asp.net version is not installed. My guess was that Windows 10 comes with 4.6, not 4.5.

Workaround:
Since a vsix file is a zip file, you can rename the file to ,zip, extract it and remove the asp.net version under dependencies the extension.vsixmanifest. Re-zip the contents and install it. Works like a charm.

**Comment by zpqrtbnk** [comment]
The VSIX has a dependency on .NET Framework Version="4.5".
Updating so that it depends on .NET Framework Version="[4.5-5.0)".
Testing...

**Comment by zpqrtbnk** [comment]
Should be "[4.5,5.0)" actually.
Will ship 2.1.4 with that setting, and all should be ok (don't have W10 to test)
