### ISSUE TITLE
Could not load control: '/UserControls/Zbu/ModelsBuilder/BuildModels.ascx'

### ISSUE THREAD

**Issue by 2014amja** [zpqrtbnk/Zbu.ModelsBuilder#63]
HI
I have Merchello installed version 1.10.1
Umbraco version 7.2.8 assembly: 1.0.5675.23466

Error: 
Could not load control: '/UserControls/Zbu/ModelsBuilder/BuildModels.ascx'. 
Error message: System.Web.HttpCompileException (0x80004005): c:\dev\Undervisning\MvcMerchelloShop\MvcMerchelloShop\MvcMerchelloShop\usercontrols\Zbu\ModelsBuilder\BuildModels.ascx(22): error CS0117: 'Zbu.ModelsBuilder.Configuration.Config' indeholder ikke en definition af 'MixinPropertiesGeneratorMode' at System.Web.Compilation.AssemblyBuilder.Compile() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at System.Web.UI.TemplateControl.LoadControl(String virtualPath) at Umbraco.Web.UI.Umbraco.Dashboard.UserControlProxy.OnInit(EventArgs e)

**Comment by zpqrtbnk** [comment]
Duplicates #61.
