### ISSUE TITLE
Install-Package fails when using Empty WebApplication

### ISSUE THREAD

**Issue by ThumNet** [zpqrtbnk/Zbu.ModelsBuilder#81]
Hi Stephan, 

Today I wanted to try the Umbraco 7.4.0-beta2 release and got an error while adding UmbracoCms using Nuget. After some investigation I found the issue is in the ModelsBuilder web.config transformation. In my case the desired node `/configuration/system.web/compilation/assemblies` didn't exist. The same goes for `/configuration/system.web/compilation/buildProviders` node. After manually creating both nodes in the web.config I was able to install UmbracoCms.

The following error is shown in the Package Manager Console:
![error-message](https://cloud.githubusercontent.com/assets/692308/12454008/f0c932b8-bf95-11e5-887c-b0e8929ffdf8.jpg)

Maybe it's possible to also create the desired nodes in the web.config.install.xdt file.

Regards,
Jeffrey

**Comment by zpqrtbnk** [comment]
Probably fixed also by [this PR](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/pull/76).

**Comment by mh0101** [comment]
Hi,

How can i fix this issue for my machine? I have created a blank MVC 4 project in VS 2015 community. I am receiving the same error using PM> Install-Package UmbracoCms -Version 7.4.0 in nuget!

I'm sorry, I could not get how to solve it by adding the above lines when I have no files in my project.

**Comment by zpqrtbnk** [comment]
There is no web.config file in your project? Then you probably first need to add a new web.config file, containing the nodes specified by the OP, and it should work. Note that all this will be fixed in the next beta.

**Comment by mh0101** [comment]
Thanks zpqrbnk. I have added these two in the config files but still getting an error. Please see this snapshot.

![error](https://cloud.githubusercontent.com/assets/1577955/12618637/a6b8287e-c50c-11e5-9405-70999c5b577f.JPG)

**Comment by mh0101** [comment]
I think I need to update the command to beta 2 specific one for PM but I don't find it on the umbraco site.

**Comment by mh0101** [comment]
Ok cool that I have found the version history on Nuget https://www.nuget.org/packages/UmbracoCms/7.4.0-beta

I'm now running PM> Install-Package UmbracoCms -Version 7.4.0-beta2 -Pre 
I hope this is ok for 7.4 beta 2 besides nuget just does not list the version number against 7.4

 PM> Install-Package UmbracoCms -Pre

![nuget error](https://cloud.githubusercontent.com/assets/1577955/12619681/ffd2477e-c510-11e5-9721-3859f1aa900e.JPG)
