### ISSUE TITLE
Error - Not found when generating models from Visual studio

### ISSUE THREAD

**Issue by ad794** [zpqrtbnk/Zbu.ModelsBuilder#89]
Hi, 

I have installed VS extension and ZBU builder version 2.1.4 every time I run the custom tool I get 404 error

`<div id="content"> 
<div class="content-container"> 
  <h3>HTTP Error 404.0 - Not Found</h3> 
  <h4>The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.</h4> `

The URL the tool is trying to hit is given below
`<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;http://aqua-lp.local:80/Umbraco/BackOffice/Zbu/ModelsBuilderApi/ValidateClientVersion</td></tr> 
    <tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\git\AquaLandingPages\AquaLandingPages\Umbraco\BackOffice\Zbu\ModelsBuilderApi\ValidateClientVersion</td></tr>`

I have been stuck on this error and really need help to progress further

MAny thanks
AD

**Comment by zpqrtbnk** [comment]
So you have installed the VS extension in VS, and the two NuGet packages into your website?

**Comment by ad794** [comment]
Thank you so much for your prompt reply. 

Yes I have VS extension 2.1.4.53 installed. and I installed ZbuModelsBuilder package installed through nuget. Is there any other nuget package that I need to install.

MAny thanks
Ad

**Comment by ad794** [comment]
Also I have tried the following three versions of ZbuModelsBuilder.

1. 2.1.3
2. 2.1.4
3. 2.1.5

But it gave me the same error with all three versions

thanks
AD

**Comment by zpqrtbnk** [comment]
As with version 2.x of the ModelsBuilder there are 2 NuGet packages that you need to install, Zbu.ModelsBuilder and Zbu.ModelsBuilder.AspNet. Could it be you're missing one?

**Comment by ad794** [comment]
Yea I havent installed ZbuModelsBuilder.AspNET so let me install that 

Thanks
AD

**Comment by ad794** [comment]
Hi Just to confirm adding the ZBUModel.AspNEt solved the issue thanks for your time and help!

I will close this issue now
