### ISSUE TITLE
Nuget package requires web.config elements

### ISSUE THREAD

**Issue by lars-erik** [zpqrtbnk/Zbu.ModelsBuilder#90]
I'm trying to install Umbraco 7.4 beta 2 using nuget in a VS 2015 project targeting runtime 4.5.2.
configuration/system.web/compilation does not have any child elements.
The modelsbuilder package fails when attempting to add to ./assemblies and ./buildProviders and nuget proceeds to roll back entire installation.
Example output:

```
install-package : An error occurred while applying transformation to 'web.config' in project 'FromModel1.Web' No element in the source document matches '/configuration/system.web/compilation/assemblies/add[@assembly='Umbraco.ModelsBuilder']'
At line:1 char:1
+ install-package umbracocms -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by zpqrtbnk** [comment]
Yup, confirmed, see http://issues.umbraco.org/issue/U4-7755 which is fixed - just need to release.
