### ISSUE TITLE
Can't see how to gain access to visual studio intellisense for generated models

### ISSUE THREAD

**Issue by a1exb1** [zpqrtbnk/Zbu.ModelsBuilder#95]
If i include all.generated.cs, i get intellisense in my views but the view fails to compile when rendered.

How do you gain access to intellisense without including that file?

**Comment by a1exb1** [comment]
fixed by: including "all.generated.cs" inside my project 

and

adding this to Web.Config -> appSettings:

<add key="Umbraco.ModelsBuilder.ModelsMode" value="Dll" />

**Comment by zpqrtbnk** [comment]
Adding what to web.config ? ;-)

**Comment by a1exb1** [comment]
Whoops haha, add:

<add key="Umbraco.ModelsBuilder.ModelsMode" value="Dll" /

To Web.config

This makes sure it doesnt compile the classes twice and throw an exception
