### ISSUE TITLE
The type or namespace could not be found for all generated models in VS2015 view editor

### ISSUE THREAD

**Issue by arievansomeren** [zpqrtbnk/Zbu.ModelsBuilder#98]
I am experiencing some issues regarding the use of the models in PureLive mode with Umbraco 7.4.1.
For some reason VS2015 will not recognize the types within the 'Umbraco.Web.PublishedContentModels' namespace while using the following inherit statement :

@inherits UmbracoTemplatePage<AnyDeclaredModel>

The 'Umbraco.Web.PublishedContentModels' is added to the ~/Views/Web.config file under 'system.web.webPages.razor/pages/namespaces' element.

I tried including the models.generated.cs into my project but this results into duplicate definition in runtime. Setting the build action to 'None' counteracts this, but won't fix my initial problem.

Is this a bug or am i missing some key configuration?

**Comment by zpqrtbnk** [comment]
This is expected. In PureLive mode, the models only exists _in memory, when the view is rendered_ and there is no way Visual Studio can recognize, know, be aware of, whatever them. And if you include the models.generated.cs files in your project, they will be compiled twice (once in memory when the view is rendered, and once in your project) resulting in duplicate definitions.

If you want models to be visible to Visual Studio you have to switch to another mode such as "Dll". In this mode, models exist _in a DLL_ that will be loaded at runtime _and_ can be referenced by Visual Studio. The only drawback is that you have to explicitely re-generate that DLL (by clicking the button in the content type editor) whenever you make changes to your content types.

Making sense?

**Comment by zpqrtbnk** [comment]
See also: http://www.zpqrtbnk.net/posts/beyond-purelive

**Comment by arievansomeren** [comment]
Brillant, great explanation in your blog post. Thanks for that!
